[package]
name = "yongle-cas-admin"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yongle-cas-types.workspace = true

[lints]
workspace = true
