[package]
name = "yongle-object"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yongle-id.workspace = true
yongle-cas-types.workspace = true
yongle-primitives.workspace = true
smol_str.workspace = true
rkyv.workspace = true
serde.workspace = true

[lints]
workspace = true
